import argparse
import json
import os
import torch
import xxhash
import tqdm
import logging
import networkx as nx
from tqdm import tqdm
import pickle as pkl
import time
import datetime
import dgl
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from collections import defaultdict
import numpy as np
valid_node_type = ['file', 'process_memory', 'task', 'mmaped_file', 'path', 'socket', 'address', 'link']
# valid_node_type = ['file', 'process_memory', 'task']
CONSOLE_ARGUMENTS = None


def hashgen(l):
    """Generate a single hash value from a list. @l is a list of
    string values, which can be properties of a node/edge. This
    function returns a single hashed integer value."""
    hasher = xxhash.xxh64()
    for e in l:
        hasher.update(e)
    return hasher.intdigest()


def parse_nodes(json_string, node_map):
    """Parse a CamFlow JSON string that may contain nodes ("activity" or "entity").
    Parsed nodes populate @node_map, which is a dictionary that maps the node's UID,
    which is assigned by CamFlow to uniquely identify a node object, to a hashed
    value (in str) which represents the 'type' of the node. """
    json_object = None
    json_object = json.loads(json_string)
    if "activity" in json_object:
        activity = json_object["activity"]
        for uid in activity:
            if not uid in node_map:  # only parse unseen nodes
                if "prov:type"  in activity[uid]:
                    # a node must have a type.
                    # record this issue if logging is turned on
                    node_map[uid] = activity[uid]["prov:type"]
                    # 事件存了"prov:type":"socket"

    if "entity" in json_object:
        entity = json_object["entity"]
        for uid in entity:
            if not uid in node_map:
                if "prov:type" in entity[uid]:
                    node_map[uid] = entity[uid]["prov:type"]


def parse_all_nodes(filename, node_map):
    """Parse all nodes in CamFlow data. @filename is the file path of
    the CamFlow data to parse. @node_map contains the mappings of all
    CamFlow nodes to their hashed attributes. """
    description = '\x1b[6;30;42m[STATUS]\x1b[0m Parsing nodes in CamFlow data from {}'.format(filename)
    pb = tqdm(desc=description, mininterval=1.0, unit=" recs")
    with open(filename, 'r') as f:
        # each line in CamFlow data could contain multiple
        # provenance nodes, we call @parse_nodes routine.
        for line in f:
            pb.update()  # for progress tracking
            parse_nodes(line, node_map)
    f.close()
    pb.close()


def parse_all_edges(inputfile, outputfile, node_map):
    """Parse all edges (including their timestamp) from CamFlow data file @inputfile
    to an @outputfile. Before this function is called, parse_all_nodes should be called
    to populate the @node_map for all nodes in the CamFlow file. If @noencode is set,
    we do not hash the nodes' original UUIDs generated by CamFlow to integers. This
    function returns the total number of valid edge parsed from CamFlow dataset.

    The output edgelist has the following format for each line, if -s is not set:
        <source_node_id> \t <destination_node_id> \t <hashed_source_type>:<hashed_destination_type>:<hashed_edge_type>:<edge_logical_timestamp>
    If -s is set, each line would look like:
        <source_node_id> \t <destination_node_id> \t <hashed_source_type>:<hashed_destination_type>:<hashed_edge_type>:<edge_logical_timestamp>:<timestamp_stats>"""
    total_edges = 0
    # smallest_timestamp = None
    # scan through the entire file to find the smallest timestamp from all the edges.
    # this step is only needed if we need to add some statistical information.
    # we will go through the CamFlow data (again) and output edgelist to a file
    output = open(outputfile, "w+")
    description = '\x1b[6;30;42m[STATUS]\x1b[0m Parsing edges in CamFlow data from {}'.format(inputfile)
    pb = tqdm(desc=description, mininterval=1.0, unit=" recs")
    with open(inputfile, 'r') as f:
        for line in f:
            pb.update()
            json_object = json.loads(line)
            if "used" in json_object:
                used = json_object["used"]
                for uid in used:
                    edgetype = "used"
                    timestamp = used[uid]["cf:id"]
                    if "prov:entity" not in used[uid]:
                        # an edge's source node must exist;
                        # if not, we will have to skip the
                        # edge. Log this issue if verbose is set.
                        continue
                    if "prov:activity" not in used[uid]:
                        # an edge's destination node must exist;
                        # if not, we will have to skip the edge.
                        # Log this issue if verbose is set
                        continue
                    srcUUID = used[uid]["prov:entity"]
                    dstUUID = used[uid]["prov:activity"]
                    # both source and destination node must
                    # exist in @node_map; if not, we will
                    # have to skip the edge. Log this issue
                    # if verbose is set.
                    if srcUUID not in node_map:
                        continue
                    else:
                        srcVal = node_map[srcUUID]
                    if dstUUID not in node_map:
                        continue
                    else:
                        dstVal = node_map[dstUUID]
                    total_edges += 1
                    if srcVal in valid_node_type and dstVal in valid_node_type:
                        output.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(total_edges,hashgen([srcUUID]), hashgen([dstUUID]), srcVal, dstVal, edgetype, timestamp))

            if "wasGeneratedBy" in json_object:
                wasGeneratedBy = json_object["wasGeneratedBy"]
                for uid in wasGeneratedBy:
                    if "prov:type" not in wasGeneratedBy[uid]:
                        continue
                    else:
                        edgetype = "wasGeneratedBy"
                    if "cf:id" not in wasGeneratedBy[uid]:
                        continue
                    else:
                        timestamp = wasGeneratedBy[uid]["cf:id"]
                    if "prov:entity" not in wasGeneratedBy[uid]:
                        continue
                    if "prov:activity" not in wasGeneratedBy[uid]:
                        continue
                    srcUUID = wasGeneratedBy[uid]["prov:activity"]
                    dstUUID = wasGeneratedBy[uid]["prov:entity"]
                    if srcUUID not in node_map:
                        continue
                    else:
                        srcVal = node_map[srcUUID]
                    if dstUUID not in node_map:
                        continue
                    else:
                        dstVal = node_map[dstUUID]
                    total_edges += 1
                    if srcVal in valid_node_type and dstVal in valid_node_type:
                        output.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(total_edges,hashgen([srcUUID]), hashgen([dstUUID]), srcVal, dstVal, edgetype, timestamp))

            if "wasInformedBy" in json_object:
                wasInformedBy = json_object["wasInformedBy"]
                for uid in wasInformedBy:
                    if "prov:type" not in wasInformedBy[uid]:
                        continue
                    else:
                        edgetype = "wasInformedBy"
                    if "cf:id" not in wasInformedBy[uid]:
                        continue
                    else:
                        timestamp = wasInformedBy[uid]["cf:id"]
                    if "prov:informant" not in wasInformedBy[uid]:
                        continue
                    if "prov:informed" not in wasInformedBy[uid]:
                        continue
                    srcUUID = wasInformedBy[uid]["prov:informant"]
                    dstUUID = wasInformedBy[uid]["prov:informed"]
                    if srcUUID not in node_map:
                        continue
                    else:
                        srcVal = node_map[srcUUID]
                    if dstUUID not in node_map:
                        continue
                    else:
                        dstVal = node_map[dstUUID]
                    total_edges += 1
                    if srcVal in valid_node_type and dstVal in valid_node_type:
                        output.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(total_edges,hashgen([srcUUID]), hashgen([dstUUID]), srcVal, dstVal, edgetype, timestamp))

            if "wasDerivedFrom" in json_object:
                wasDerivedFrom = json_object["wasDerivedFrom"]
                for uid in wasDerivedFrom:
                    if "prov:type" not in wasDerivedFrom[uid]:
                        continue
                    else:
                        edgetype = "wasDerivedFrom"
                    if "cf:id" not in wasDerivedFrom[uid]:
                        continue
                    else:
                        timestamp = wasDerivedFrom[uid]["cf:id"]
                    if "prov:usedEntity" not in wasDerivedFrom[uid]:
                        continue
                    if "prov:generatedEntity" not in wasDerivedFrom[uid]:
                        continue
                    srcUUID = wasDerivedFrom[uid]["prov:usedEntity"]
                    dstUUID = wasDerivedFrom[uid]["prov:generatedEntity"]
                    if srcUUID not in node_map:
                        continue
                    else:
                        srcVal = node_map[srcUUID]
                    if dstUUID not in node_map:
                        continue
                    else:
                        dstVal = node_map[dstUUID]
                    total_edges += 1
                    if srcVal in valid_node_type and dstVal in valid_node_type:
                        output.write("{}\t{}\t{}\t{}\t{}\t{}\t{}\n".format(total_edges,hashgen([srcUUID]), hashgen([dstUUID]), srcVal, dstVal, edgetype, timestamp))

            if "wasAssociatedWith" in json_object:
                wasAssociatedWith = json_object["wasAssociatedWith"]
                for uid in wasAssociatedWith:
                    if "prov:type" not in wasAssociatedWith[uid]:
                        continue
                    else:
                        edgetype = "wasAssociatedWith"
                    if "cf:id" not in wasAssociatedWith[uid]:
                        continue
                    else:
                        timestamp = wasAssociatedWith[uid]["cf:id"]
                    if "prov:agent" not in wasAssociatedWith[uid]:
                        continue
                    if "prov:activity" not in wasAssociatedWith[uid]:
                        continue
                    srcUUID = wasAssociatedWith[uid]["prov:agent"]
                    dstUUID = wasAssociatedWith[uid]["prov:activity"]
                    if srcUUID not in node_map:
                        continue
                    else:
                        srcVal = node_map[srcUUID]
                    if dstUUID not in node_map:
                        continue
                    else:
                        dstVal = node_map[dstUUID]
                    total_edges += 1
                    if srcVal in valid_node_type and dstVal in valid_node_type:
                        output.write("{}\t{}\t{}:{}:{}:{}\n".format(hashgen([srcUUID]), hashgen([dstUUID]), srcVal, dstVal,edgetype, timestamp))
    f.close()
    output.close()
    pb.close()
    return total_edges

def read_single_graph(file_name):
    graph = []
    edge_cnt = 0
    with open(file_name, 'r') as f:
        for line in f:
            try:
                edge = line.strip().split("\t")
                new_edge = [edge[0], edge[1]]
                attributes = edge[2].strip().split(":")
                source_node_type = attributes[0]
                destination_node_type = attributes[1]
                edge_type = attributes[2]
                edge_order = attributes[3]

                new_edge.append(source_node_type)
                new_edge.append(destination_node_type)
                new_edge.append(edge_type)
                new_edge.append(edge_order)
                graph.append(new_edge)
                edge_cnt += 1
            except:
                print("{}".format(line))
    #new_edge 0 1 2 3分别存放src_attr dst_attr edge_type edge_order
    f.close()
    graph.sort(key=lambda e: e[5])
    return graph


# def process_graph(name):
#     graph = read_single_graph(name)
#     result_graph = nx.DiGraph()
#     cnt = 0
#     for num, edge in enumerate(graph):
#         cnt += 1
#         src, dst, src_type, dst_type, edge_type = edge[:5]
#         if src_type in valid_node_type and dst_type in valid_node_type:
#             if not result_graph.has_node(src):
#                 result_graph.add_node(src, type=src_type)
#             if not result_graph.has_node(dst):
#                 result_graph.add_node(dst, type=dst_type)
#             if not result_graph.has_edge(src, dst):
#                 result_graph.add_edge(src, dst, type=edge_type)
#     return cnt, result_graph


node_type_list = []
edge_type_list = []
node_type_dict = {}
edge_type_dict = {}


def format_graph(g, name):
    new_g = nx.DiGraph()
    node_map = {}
    node_cnt = 0
    for n in g.nodes:
        node_map[n] = node_cnt
        new_g.add_node(node_cnt, type=g.nodes[n]['type'])
        node_cnt += 1
    for e in g.edges:
        new_g.add_edge(node_map[e[0]], node_map[e[1]], type=g.edges[e]['type'])
    for n in new_g.nodes:
        node_type = new_g.nodes[n]['type']
        if not node_type in node_type_dict:
            node_type_list.append(node_type)
            node_type_dict[node_type] = 1
        else:
            node_type_dict[node_type] += 1
    for e in new_g.edges:
        edge_type = new_g.edges[e]['type']
        if not edge_type in edge_type_dict:
            edge_type_list.append(edge_type)
            edge_type_dict[edge_type] = 1
        else:
            edge_type_dict[edge_type] += 1
    for n in new_g.nodes:
        new_g.nodes[n]['type'] = node_type_list.index(new_g.nodes[n]['type'])
    for e in new_g.edges:
        new_g.edges[e]['type'] = edge_type_list.index(new_g.edges[e]['type'])
    with open('{}.json'.format(name), 'w', encoding='utf-8') as f:
        json.dump(nx.node_link_data(new_g), f)

def one_hot_encode(df, column_name, max_dim=8):
    # 对列进行One-Hot编码
    encoder = OneHotEncoder(sparse_output=False)
    encoded = encoder.fit_transform(df[[column_name]])
    if encoded.shape[1] < max_dim:
        padding = np.zeros((encoded.shape[0], max_dim - encoded.shape[1]))
        encoded = np.hstack([encoded, padding])
    elif encoded.shape[1] > max_dim:
        encoded = encoded[:, :max_dim]
    print(f"{column_name} is ready")
    return encoded

def get_cnt(df, attr_type):
    df[attr_type] = pd.Categorical(df[attr_type]).codes
    df[attr_type] = list(one_hot_encode(df, attr_type))
    return df

def finish_graph(input,output):
    cnt = 150
    for i in tqdm(range(cnt)):
        g_nodes = []
        g_edges_set = set()
        map_a = defaultdict(list)
        map_b = defaultdict(list)
        input_file_name = '{}{}.log'.format(input, i + 1)
        output_file_name = '{}graph{}.pkl'.format(output, i + 1)
        with open(input_file_name, encoding='utf-8') as f:
            # 读取数据
            df = pd.read_csv(f,
                             sep='\t',
                             names=['uuid', 'src_id', 'dst_id', 'srcVal', 'dstVal', 'edgetype', 'timestamp'])
            
            # 获取各列的计数（可以根据需要调整）
            df = get_cnt(df, 'srcVal')
            df = get_cnt(df, 'dstVal')
            df = get_cnt(df, 'edgetype')            
            # 获取每个uuid的最后一条记录
            df_last = df.drop_duplicates(subset='uuid', keep='last')

            for _, row in df_last.iterrows():
                # 获取编码后的各个属性并转为Tensor
                uuid = row['uuid']
                src_id = row['src_id']
                dst_id = row['dst_id']
                src_val = row['srcVal']
                dst_val = row['dstVal']
                edge_type = row['edgetype']
                src_val_embed = torch.tensor(src_val, dtype=torch.int32)
                dst_val_embed = torch.tensor(dst_val, dtype=torch.int32)
                edgetype_embed = torch.tensor(edge_type, dtype=torch.int32)
                sub_g_embedding = torch.cat([src_val_embed, dst_val_embed, edgetype_embed], dim=0)
                # 将最终的嵌入存储到字典中，使用uuid作为键
                g_nodes.append((uuid, {"attr": sub_g_embedding}))
                map_a[dst_id].append(uuid)
                map_b[src_id].append(uuid)

            for dst in tqdm(map_a, total=len(map_a)):
                if dst in map_b:
                    cnt_list_a = map_a[dst]
                    cnt_list_b = map_b[dst]
                    for event_src in cnt_list_a:
                        for event_dst in cnt_list_b:
                            if event_src != event_dst and (event_src, event_dst) not in g_edges_set:
                                g_edges_set.add((event_src, event_dst))
                # Save g_nodes to a pickle file
            g = nx.DiGraph()
            for node in g_nodes:
                g.add_node(node[0], attr=node[1]["attr"].float())
            for edge in g_edges_set:
                g.add_edge(edge[0], edge[1])
            train_g = dgl.from_networkx(g, node_attrs=['attr'])
            g_degree = train_g.in_degrees() + train_g.out_degrees()
            zero_degree_count = (g_degree == 0).sum().item()
            print(f"Number of nodes: {train_g.number_of_nodes()}")
            print(f"Number of nodes with zero degree: {zero_degree_count}")
            train_g = dgl.add_self_loop(train_g)
            with open(output_file_name, 'wb') as f:
                pkl.dump(train_g, f)  
            print(f"Graph {i} data saved. \n")        



            


# def find_entity_pair(input_file_name):
#     map_a = defaultdict(list)
#     map_b = defaultdict(list)
#     g_edges_set = set()
#     cnt = 0 
#     if os.path.exists(input_file_name):
#         with open(input_file_name, encoding='utf-8') as f:
#             for line in f:
#                 cnt += 1
#                 uuid, src, dst, srcVal, dstVal, edgetype, time = line.strip().split('\t')
#                 map_a[dst].append(cnt)
#                 map_b[src].append(cnt)
#             for dst in tqdm(map_a, total=len(map_a)):
#                 if dst in map_b:
#                     cnt_list_a = map_a[dst]
#                     cnt_list_b = map_b[dst]
#                     for event_src in cnt_list_a:
#                         for event_dst in cnt_list_b:
#                             if event_src != event_dst and (event_src, event_dst) not in g_edges_set:
#                                 g_edges_set.add((event_src, event_dst))
#         with open(output_file_name, 'wb') as f:
#             pkl.dump(g_edges_set, f)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Convert CamFlow LOG')

    args = parser.parse_args()
    args.input = './dataset/wget/raw/'
    args.output = './dataset/wget/processed/'
    args.entity_output = './dataset/wget/entity_pair/'
    args.final_output = './dataset/wget/final/'
    if not os.path.exists(args.input):
        os.mkdir(args.input)
    if not os.path.exists(args.output):
        os.mkdir(args.output)
    if not os.path.exists(args.entity_output):
        os.mkdir(args.entity_output)
    if not os.path.exists(args.final_output):
        os.mkdir(args.final_output)
    CONSOLE_ARGUMENTS = args
    cnt = 0
    # 从日志当中预处理出需要的属性
    # for fname in os.listdir(args.input):
    #     cnt += 1
    #     node_map = dict()
    #     parse_all_nodes(args.input + '/{}'.format(fname), node_map)
    #     parse_all_edges(args.input + '/{}'.format(fname), args.output + '/{}.log'.format(cnt), node_map)
    # assert(cnt == 150)
    input = args.output
    output = args.entity_output
    # line_cnt = 0
    # entity_pair
    finish_graph(input,output)

    # 预处理后的建图    
    # for i in tqdm(range(cnt)):
    #     single_cnt, result_graph = process_graph('{}{}.log'.format(input, i + 1))
    #     format_graph(result_graph, '{}{}'.format(base, i))
    #     line_cnt += single_cnt

    # print(line_cnt // 150)
    # print(len(node_type_list))
    # print(node_type_dict)
    # print(len(edge_type_list))
    # print(edge_type_dict)

